
// Generated by MyGeneration Version # (1.3.0.9)

using System;
using System.Collections.Generic;

namespace FileOrganizer.BL
{
    public partial class View_ListStorageItemRow
    {
        public string GetPathIcon()
        {
            return StorageItemRow.GetPathIconForStorageItem(this.s_FullPath, this.s_ItemName);
        }
    }
}
